package:
  name: klb
  version: 0.0

source:
  path: ../../

build:
  number: 0
  string: {{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - gcc 4.8.5
    - bzip2
    - zlib
  
  run:
    - libgcc 4.8.5
    
    # These aren't needed at runtime because they were statically linked
    # - bzip2
    # - zlib

about:
  home: https://bitbucket.org/fernandoamat/keller-lab-block-filetype
  license: BSD
  license_file: LICENSE.txt
  summary: Keller Lab Block file type (.klb) C++11 library
