/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.janelia.simview.klb.jni;

public interface KlbConstants {
  public final static int KLB_DATA_DIMS = KlbJNI.KLB_DATA_DIMS_get();
  public final static int KLB_DEFAULT_HEADER_VERSION = KlbJNI.KLB_DEFAULT_HEADER_VERSION_get();
}
