/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.janelia.simview.klb.jni;

public enum KlbCompressionType {
  NONE(KlbJNI.NONE_get()),
  BZIP2(KlbJNI.BZIP2_get()),
  ZLIB(KlbJNI.ZLIB_get());

  public final int swigValue() {
    return swigValue;
  }

  public static KlbCompressionType swigToEnum(int swigValue) {
    KlbCompressionType[] swigValues = KlbCompressionType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (KlbCompressionType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + KlbCompressionType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private KlbCompressionType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private KlbCompressionType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private KlbCompressionType(KlbCompressionType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

