/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.janelia.simview.klb.jni;

public class KlbImageIO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KlbImageIO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KlbImageIO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KlbJNI.delete_KlbImageIO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeader(KlbImageHeader value) {
    KlbJNI.KlbImageIO_header_set(swigCPtr, this, KlbImageHeader.getCPtr(value), value);
  }

  public KlbImageHeader getHeader() {
    long cPtr = KlbJNI.KlbImageIO_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new KlbImageHeader(cPtr, false);
  }

  public void setNumThreads(int value) {
    KlbJNI.KlbImageIO_numThreads_set(swigCPtr, this, value);
  }

  public int getNumThreads() {
    return KlbJNI.KlbImageIO_numThreads_get(swigCPtr, this);
  }

  public KlbImageIO() {
    this(KlbJNI.new_KlbImageIO__SWIG_0(), true);
  }

  public KlbImageIO(String filename_) {
    this(KlbJNI.new_KlbImageIO__SWIG_1(filename_), true);
  }

  public String getFilename() {
    return KlbJNI.KlbImageIO_getFilename(swigCPtr, this);
  }

  public void setFilename(String filename_) {
    KlbJNI.KlbImageIO_setFilename(swigCPtr, this, filename_);
  }

  public int readHeader() {
    return KlbJNI.KlbImageIO_readHeader__SWIG_0(swigCPtr, this);
  }

  public int readHeader(String filename_) {
    return KlbJNI.KlbImageIO_readHeader__SWIG_1(swigCPtr, this, filename_);
  }

  public int writeImage(byte[] BYTE, int numThreads) {
    return KlbJNI.KlbImageIO_writeImage(swigCPtr, this, BYTE, numThreads);
  }

  public int readImage(byte[] BYTE, KlbRoi ROI, int numThreads) {
    return KlbJNI.KlbImageIO_readImage(swigCPtr, this, BYTE, KlbRoi.getCPtr(ROI), ROI, numThreads);
  }

  public int readImageFull(byte[] BYTE, int numThreads) {
    return KlbJNI.KlbImageIO_readImageFull(swigCPtr, this, BYTE, numThreads);
  }

}
